name: extract comments

on:
  schedule:
    - cron: "18 22 * * *"
  workflow_dispatch:

jobs:
  run_script:
    name: Ejecutar script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Cambia a la versión de Python que necesites

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python extract_comments.py
        
      - name: Eliminar archivo existente
        run: rm -f comments.json
      
      - name: Mover comments.json al directorio raíz
        run: mv comments.json $GITHUB_WORKSPACE/comments.json
